# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
    Function:
        Environment:
            Variables:
                SQS_URL: !Ref SavePrefsQueue

Resources:
    SavePrefsQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: deferred-save-prefs-queue
            VisibilityTimeout: 601
    RetrievePrefsFunction2:
        Type: AWS::Serverless::Function
        Properties:
            Handler: retrieve-prefs.default
            Runtime: nodejs16.x
            CodeUri: ./dist/retrieve-prefs
            Timeout: 5
            MemorySize: 128
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                - SecretsManagerReadWrite
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-retrieve-prefs-2
            AutoPublishAlias: live
            FunctionUrlConfig:
                AuthType: NONE
    StartSavePrefsFunction2:
        Type: AWS::Serverless::Function
        Properties:
            Handler: start-save-prefs.default
            Runtime: nodejs16.x
            CodeUri: ./dist/start-save-prefs
            Timeout: 3
            MemorySize: 128
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                - SecretsManagerReadWrite
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-start-save-prefs-2
            AutoPublishAlias: live
            FunctionUrlConfig:
                AuthType: NONE
    ProcessSavePrefsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: process-save-prefs.default
            Runtime: nodejs12.x
            CodeUri: ./dist/process-save-prefs
            MemorySize: 128
            ReservedConcurrentExecutions: 1
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - SecretsManagerReadWrite
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: process-save-prefs
            Timeout: 60
            Events:
                SQSMapperRequestedEvent:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt SavePrefsQueue.Arn
                        # BatchSize: 1
