# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API endpoint to register a userid / username mapping

Globals:
    Api:
        # API Gateway regional endpoints
        EndpointConfiguration: EDGE
        Cors:
            AllowMethods: "'*'"
            AllowHeaders: "'*'"
            AllowOrigin: "'*'"
    Function:
        Environment:
            Variables:
                SQS_URL: !Ref SavePrefsQueue

Resources:
    SavePrefsQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: deferred-save-prefs-queue
            VisibilityTimeout: 601
    RetrievePrefsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: retrieve-prefs.default
            Runtime: nodejs10.x
            Timeout: 3
            MemorySize: 128
            CodeUri: ./dist/retrieve-prefs
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                - SecretsManagerReadWrite
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-retrieve-prefs
            Events:
                SavePrefsResource:
                    Type: Api
                    Properties:
                        Path: /get/{proxy+}
                        Method: any
    StartSavePrefsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: start-save-prefs.default
            Runtime: nodejs10.x
            Timeout: 3
            MemorySize: 128
            CodeUri: ./dist/start-save-prefs
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                - SecretsManagerReadWrite
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-start-save-prefs
            Events:
                SavePrefsResource:
                    Type: Api
                    Properties:
                        Path: /post/{proxy+}
                        Method: any
    ProcessSavePrefsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: process-save-prefs.default
            Runtime: nodejs10.x
            CodeUri: ./dist/process-save-prefs
            MemorySize: 128
            ReservedConcurrentExecutions: 1
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - SecretsManagerReadWrite
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: process-save-prefs
            Timeout: 60
            Events:
                SQSMapperRequestedEvent:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt SavePrefsQueue.Arn
                        # BatchSize: 1

Outputs:
    SavePrefsApi:
        Description: URL to save prefs
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/preferences'
        Export:
            Name: SavePrefsApi
